title: lmao nya
author: vivi
email: your-email@bigboi.com
description: > # this means to ignore newlines until "baseurl:"
  my site is aha very cool very gamer :flushed:

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
